import Head from 'next/head'
import Land from './Land/Land'
import Service from './Service/Service'
import About from './About/About'
import Footer from './Footer/Footer'
import React from 'react'
import Testimonials from './Testimonials/Testimonials'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Land/>     
<About/>
      <Service/>
      <Testimonials/>
      <Footer/>

    </main>
    </>
  )
}
